name: Python Environment Setup
on: 
  push:
    branches:
      - main  # 当推送到 main 分支时触发
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
