name: Hexo pages

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: false  # 禁用子模块检查

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: 安装hexo
        run: |
          
          sudo apt install python3
          py md5.py

      - name: 设置Git配置
        run: |
          git config --global user.name 'wyxdlz54188'
          git config --global user.email 'liyuqili_1379zi@qq.com'
          
      - name: 推送到 GitHub Pages
        run: |
         git init
         git add .
         git commit -m "通过工作流创建"
         git remote add origin https://${{ secrets.GH_TOKEN }}@github.com/wyxdlz54188/Penjailbreak_YD.git
         git push origin HEAD:main -f
         
